title: Code BEAM America
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Code BEAM America, a conference organised by Code Sync. Code BEAM America is the premiere Erlang and Elixir conference in America, bringing the best speakers in the community together, for two days of first-rate BEAM-related talks and two days of tutorials.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codebeamamerica.com" # the base hostname & protocol for your site

logo: "./assets/images/logo2022.png"

# google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: [archives]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/codebeamio
    username: codebeamio
    card: image

# Build settings
markdown: kramdown
permalink: pretty

collections:
  participants:
    output: true
  keynotes:
    output: true
  trainers:
    output: true
  trainings:
    output: true
  talks:
    output: true
  posts:
    output: true
  videos:
    output: true
#  archive:
#    output: true

defaults:
  - scope:
      path: ""
      type: "participants"
    values:
      layout: "participant"
  - scope:
      path: ""
      type: "trainings"
    values:
      layout: "training"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"
  - scope:
      path: ""
      type: "keynotes"
    values:
      layout: "talk"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
#  - scope:
#      path: ""
#      type: "archives"
#    values:
#      layout: "archive"
  - scope:
      path: ""
    values:
      layout: "default"

# Google Map JS api
# This is my api for this template
key-api: AIzaSyBf-F7nBzxi_73uI9QUxRQ-cNihYtlZ_AA
map-text: Computer History Museum
map-text-location: 41401 N Shoreline Blvd, Mountain View, CA 94043
map-lat: 37.4145135
map-lng: -122.0787026
