homepage_settings:
  countdown:
    show: true
    timezone: America/Los_Angeles
    deadline: 2024-11-06 08:00
  modal:
    show: false
    delay: 5000
  testimonials:
    show: true
    title: "What Attendees think about the event?"
  gallery:
    show: true
    title: "Code BEAM America 2024"
