homepage_settings:
  countdown:
    show: false
    timezone: Europe/Berlin
    deadline: 2024-10-14 12:00
  modal:
    show: false
    delay: 5000
  testimonials:
    show: true
    title: "What Attendees think about the event?"
  gallery:
    show: true
    title: "Code BEAM America 2024"
