---
trainers:
- _participants/sophie-debenedetto.md
- _participants/steven-nunez.md
- _participants/Francesco-cesarini.md
- _participants/zack-kayser.md
- _participants/ethan-gunderson.md
- _participants/bruce-tate.md
- _participants/frank-hunleth.md
