---
trainings:
- training: _trainings/thinking-in-elixir.md
  start: 2025-03-04 09:00:00
  end: 2025-03-05 17:00:00
  timezone: PST (SF time)
- training: _trainings/GRiSP-hands-on.md
  start: 2025-03-05 09:00:00
  end: 2025-03-05 17:00:00
  timezone: PST (SF time)
- training: _trainings/building-data-driven-workflows-in-broadway.md
  start: 2025-03-05 09:00:00
  end: 2025-03-05 17:00:00
  timezone: PST (SF time)
- training: _trainings/supercharge-your-elixir-apps-with-ash.md
  start: 2025-03-05 09:00:00
  end: 2025-03-05 17:00:00
  timezone: PST (SF time)



# Below values need to be written down manually according to 
# event specific timezone and dates
# timezone - timezone of the event e.g. EST
# start - start date and time of the event !!! time in 24-hour format !!!
# end - end date and time of the event !!! time in 24-hour format !!!
