---
trainers:
- _participants/bruce-tate.md
- _participants/sasa-juric.md
- _participants/brooklin-myers.md
- _participants/dmytro-lytovchenko.md
- _participants/brujo-benavides.md
- _participants/pablo-costas.md
- _participants/michael-lubas.md
